kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auto-user-role
  namespace: auto-user

rules:
- apiGroups: ["", "apps"]
  resources: ["pods", "deployments", "services"]
  verbs: ["get", "list", "create", "update"]
